-- MySQL Script generated by MySQL Workbench
-- 05/25/15 15:48:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project` ;

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Person` ;

CREATE TABLE IF NOT EXISTS `project`.`Person` (
  `personId` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`personId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Student` ;

CREATE TABLE IF NOT EXISTS `project`.`Student` (
  `studentId` INT NOT NULL,
  `Person_personId` INT NULL,
  PRIMARY KEY (`studentId`),
  INDEX `fk_Student_Person_idx` (`Person_personId` ASC),
  CONSTRAINT `fk_Student_Person`
    FOREIGN KEY (`Person_personId`)
    REFERENCES `project`.`Person` (`personId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`registration` ;

CREATE TABLE IF NOT EXISTS `project`.`registration` (
  `DateOfRegistration` DATETIME NOT NULL,
  `registraion_number` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`registraion_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`course` ;

CREATE TABLE IF NOT EXISTS `project`.`course` (
  `courseid` VARCHAR(45) NOT NULL,
  `registration_registraion_number` INT NULL,
  PRIMARY KEY (`courseid`),
  INDEX `fk_course_registration1_idx` (`registration_registraion_number` ASC),
  CONSTRAINT `fk_course_registration1`
    FOREIGN KEY (`registration_registraion_number`)
    REFERENCES `project`.`registration` (`registraion_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`Employee` ;

CREATE TABLE IF NOT EXISTS `project`.`Employee` (
  `employeeId` INT NOT NULL,
  `type` CHAR(1) NOT NULL,
  `Person_personId` INT NULL,
  `course_courseid` VARCHAR(45) NULL,
  PRIMARY KEY (`employeeId`),
  INDEX `fk_Employee_Person1_idx` (`Person_personId` ASC),
  INDEX `fk_Employee_course1_idx` (`course_courseid` ASC),
  CONSTRAINT `fk_Employee_Person1`
    FOREIGN KEY (`Person_personId`)
    REFERENCES `project`.`Person` (`personId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_course1`
    FOREIGN KEY (`course_courseid`)
    REFERENCES `project`.`course` (`courseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`grade` ;

CREATE TABLE IF NOT EXISTS `project`.`grade` (
  `grade` INT(2) NULL,
  `semster` CHAR(6) NOT NULL,
  `year` INT(4) NOT NULL,
  PRIMARY KEY (`semster`, `year`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`stu_gra_reg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`stu_gra_reg` ;

CREATE TABLE IF NOT EXISTS `project`.`stu_gra_reg` (
  `idstu_gra_reg` INT NULL,
  `grade_semster` CHAR(6) NULL,
  `grade_year` INT(4) NULL,
  `Student_studentId` INT NULL,
  `registration_registraion_number` INT NULL,
  INDEX `fk_stu_gra_reg_grade1_idx` (`grade_semster` ASC, `grade_year` ASC),
  INDEX `fk_stu_gra_reg_Student1_idx` (`Student_studentId` ASC),
  CONSTRAINT `fk_stu_gra_reg_grade1`
    FOREIGN KEY (`grade_semster` , `grade_year`)
    REFERENCES `project`.`grade` (`semster` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_gra_reg_Student1`
    FOREIGN KEY (`Student_studentId`)
    REFERENCES `project`.`Student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_gra_reg_registration1`
    FOREIGN KEY (`registration_registraion_number`)
    REFERENCES `project`.`registration` (`registraion_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`lesson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`lesson` ;

CREATE TABLE IF NOT EXISTS `project`.`lesson` (
  `duration` TIME NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `credit` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `course_courseid` VARCHAR(45) NULL,
  PRIMARY KEY (`date`, `time`),
  INDEX `fk_lesson_course1_idx` (`course_courseid` ASC),
  CONSTRAINT `fk_lesson_course1`
    FOREIGN KEY (`course_courseid`)
    REFERENCES `project`.`course` (`courseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`division` ;

CREATE TABLE IF NOT EXISTS `project`.`division` (
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `lesson_startTime` VARCHAR(45) NULL,
  `course_courseid` VARCHAR(45) NOT NULL,
  `lesson_date` VARCHAR(45) NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_division_course1`
    FOREIGN KEY (`course_courseid`)
    REFERENCES `project`.`course` (`courseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_division_lesson1`
    FOREIGN KEY (`lesson_date` , `lesson_startTime`)
    REFERENCES `project`.`lesson` (`date` , `time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`building` ;

CREATE TABLE IF NOT EXISTS `project`.`building` (
  `buildingName` CHAR(1) NOT NULL,
  `lesson_date` VARCHAR(45) NULL,
  `lesson_startTime` VARCHAR(45) NULL,
  PRIMARY KEY (`buildingName`),
  INDEX `fk_building_lesson1_idx` (`lesson_date` ASC, `lesson_startTime` ASC),
  CONSTRAINT `fk_building_lesson1`
    FOREIGN KEY (`lesson_date` , `lesson_startTime`)
    REFERENCES `project`.`lesson` (`date` , `time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project`.`location` ;

CREATE TABLE IF NOT EXISTS `project`.`location` (
  `roomNumber` INT(3) NOT NULL,
  `range` VARCHAR(2) NOT NULL,
  `building_buildingName` CHAR(1) NULL,
  PRIMARY KEY (`roomNumber`),
  INDEX `fk_location_building1_idx` (`building_buildingName` ASC),
  CONSTRAINT `fk_location_building1`
    FOREIGN KEY (`building_buildingName`)
    REFERENCES `project`.`building` (`buildingName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
